"""init6db

Revision ID: 618d7d2a833d
Revises: dd8b882ea660
Create Date: 2025-09-21 16:39:59.021830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618d7d2a833d'
down_revision: Union[str, Sequence[str], None] = 'dd8b882ea660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=1, nullable=False),
    sa.Column('name', sa.String(), nullable=0),
    sa.Column('email', sa.String(), nullable=0),
    sa.Column('password', sa.String(), nullable=0),
    sa.Column('admin', sa.Boolean(), nullable=0),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
